on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: Lint commits
permissions:
  contents: read
  pull-requests: write
jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fixup git permissions
        # https://github.com/actions/checkout/issues/766
        shell: bash
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/setup-node@v4.1.0
      - run: npm install --save-dev @commitlint/cli @commitlint/config-conventional conventional-changelog-conventionalcommits
      - run: npx commitlint --from HEAD~${{ github.event.pull_request.commits || 1 }} --to HEAD
